services:
  api:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ../:/app
    working_dir: /app
    command: air
  db:
    image: postgres:17.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: menta-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: